### ISSUE TITLE
Typo on installation heading?

### ISSUE THREAD

**Issue by BBoal** [hrs/docsim#20]
Hi Harry, thank you for sharing your work.
Like mentioned on the title, I think where you wrote:
`go install github.com/hrs/docsim/docsim@latest`
it should instead be:
`go install github.com/hrs/docsim@latest`

Best regards,
BB

**Comment by hrs** [comment]
Whoops, good catch @BBoal! I've [fixed that](https://github.com/hrs/docsim/commit/e54865cf37c03328e6c32439e1bc393283bd420f). Thanks for letting me know!
